### PR TITLE
[GITHUB-2] Flatten vars

### PR DESCRIPTION
**Pull request by lobsterdore**
Removes top level hash and hash behaviour merge references from
role.

Also incorporated some Molecule fixes for OSX, switch to none
syslog driver and Ansible 2.4 by default which gets around
a Docker for OSX issue.

### CODE REVIEW

**Comment by racer1680** [comment]
I think removing top level hash will harm SAnsible

**Comment by lobsterdore** [comment]
As discussed elsewhere, we are going ahead with the flattening to make us compatible with the rest of the Ansible world.

**Comment by racer1680** [comment]
Let's vote

**Comment by lobsterdore** [comment]
We are flatting all the things 👍

**Pull request merged**
